ice_baby.core_flow_ing_raw.raw_bptransactextensio
ice_baby.core_flow_ing_raw.raw_bptransactdiscext
raw_bpretaillineitem переименовать
ice_baby.core_flow_ing_raw.raw_bplineitemextensio
ice_baby.core_flow_ing_raw.raw_bplineitemdiscount
ice_baby.core_flow_ing_raw.raw_bplineitemdiscext
ice_baby.core_flow_ing_raw.raw_bptender переименовать
ice_baby.core_flow_ing_raw.raw_bptenderextensions
